# Generated by Django 4.1.7 on 2023-02-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockSentiment', '0003_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='beta',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='debt',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='dividendPerShare',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='equity',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='high',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='low',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='open',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='returnOnEquity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='value',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
