# Generated by Django 4.1.7 on 2023-02-26 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockSentiment', '0004_company_beta_company_debt_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lastModified',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 17, 38, 11, 384528)),
            preserve_default=False,
        ),
    ]
