# Generated by Django 4.1.7 on 2023-02-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockSentiment', '0005_company_lastmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='high',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='company',
            name='low',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='company',
            name='open',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='company',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
