# Generated by Django 4.1.7 on 2023-02-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockSentiment', '0006_alter_company_high_alter_company_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='debt',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
