# Generated by Django 4.1.7 on 2023-02-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockSentiment', '0007_alter_company_debt_alter_company_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='debt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='equity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
