# Generated by Django 4.1.7 on 2023-02-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockSentiment', '0008_alter_company_debt_alter_company_equity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdated', models.DateTimeField()),
                ('apiCalls', models.IntegerField()),
            ],
        ),
    ]
