# Generated by Django 4.1.7 on 2023-02-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockSentiment', '0009_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='high',
        ),
        migrations.RemoveField(
            model_name='company',
            name='low',
        ),
        migrations.RemoveField(
            model_name='company',
            name='open',
        ),
        migrations.RemoveField(
            model_name='company',
            name='price',
        ),
        migrations.CreateModel(
            name='CompanyStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=8)),
                ('high', models.DecimalField(decimal_places=4, max_digits=8)),
                ('low', models.DecimalField(decimal_places=4, max_digits=8)),
                ('close', models.DecimalField(decimal_places=4, max_digits=8)),
                ('adjustedClose', models.DecimalField(decimal_places=4, max_digits=8)),
                ('sma', models.PositiveIntegerField()),
                ('interval', models.CharField(choices=[('daily', 'daily'), ('60 minutes', '60 minutes'), ('15 minutes', '15 minutes'), ('5 minutes', '5 minutes'), ('1 minute', '1 minute')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockSentiment.company')),
            ],
        ),
    ]
