# Generated by Django 4.1.7 on 2023-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockSentiment', '0010_remove_company_high_remove_company_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystockdata',
            name='sma',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
